oboero/models/verb.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from oboero import db

class Verb(db.Model):
    __tablename__ = "verb"

    def __dir__(self):
        return ["casual", "te", "potential", "conditional", "passive", "causative"]

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    teinei = db.Column(db.String(25), nullable=False)  # ikimasu
    casual = db.Column(db.String(25), nullable=False)  # iku
    te = db.Column(db.String(25), nullable=False)  # itte
    potential = db.Column(db.String(25), nullable=False)  # ikeru
    conditional = db.Column(db.String(25), nullable=False)  # ikeba
    passive = db.Column(db.String(25), nullable=False)  # ikareru
    causative = db.Column(db.String(25), nullable=False)  # ikaseru

oboero/views/admin.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import render_template, request, redirect, url_for
from flask.blueprints import Blueprint
from .. import db
from oboero.models.verb import Verb
from oboero.services.verb_service import VerbService
blueprint = Blueprint('admin', __name__)


@blueprint.route('/verb')
def verb_list():
    verbs = db.session.query(Verb).all()

    return render_template('verb/index.html', verb="VeRb", verbs=verbs)


@blueprint.route('/verb/add')
def verb_add():
    return render_template('verb/add.html')


@blueprint.route('/verb/new', methods=['POST'])
def verb_new():
    verb_service = VerbService()
    teinei = request.form.get('teinei')
    group = request.form.get('group', type=int)
    VerbService().add_word(teinei, group)
    db.session.commit()
    return redirect(url_for('admin.verb_list'))

oboero/views/verb.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import jsonify
from flask.blueprints import Blueprint
from oboero.services.verb_service import VerbService
blueprint = Blueprint('verb', __name__)


@blueprint.route('/random')
def random():
    verb, form_type = VerbService().get_random()
    conjugated_form = getattr(verb, form_type)
    return jsonify(formal=verb.teinei, type=form_type, conjugated=conjugated_form)

oboero/templates/verb/add.html
    {% extends "_layout/_base.html" %}

    {% block css %}
        .form-cntr {
            margin-top: 50px;
            width: 100%;
        }

        form {
            margin: 0 auto;
            padding: 20px;
        }

    {% endblock %}

    {% block content %}
    <div class="form-cntr">
    <form class="pure-form pure-form-stacked" action="{{url_for('admin.verb_new')}}" method="post">
        <fieldset>
            <legend>Add New Verb</legend>

            <label for="teinei">丁寧な形</label>
            <input id="teinei" type="text" name="teinei" placeholder="e.g., 行き">

            <label for="group">Group</label>
            <select id="group" name="group">
                <option value="1">Group 1</option>
                <option value="2">Group 2</option>
                <option value="3">Group 3</option>
            </select>

            <button type="submit" class="pure-button pure-button-primary">Add!</button>
        </fieldset>
    </form>
    </div>
    {% endblock %}

oboero/templates/verb/index.html
    {% extends "_layout/_base.html" %}
    {% block content %}
    <table class="pure-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Teinei</th>
                <th>Casual</th>
                <th>Te</th>
                <th>Potential</th>
                <th>Conditional</th>
                <th>Passive</th>
                <th>Causative</th>
            </tr>
        </thead>
        <tbody>
        {% for v in verbs %}
            <tr>
                <td>{{ v.id }}</td>
                <td>{{ v.teinei }}</td>
                <td>{{ v.casual }}</td>
                <td>{{ v.te }}</td>
                <td>{{ v.potential }}</td>
                <td>{{ v.conditional }}</td>
                <td>{{ v.passive }}</td>
                <td>{{ v.causative }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr>
    <a class="pure-button .button-secondary" href="{{ url_for('admin.verb_add') }}">+ New Verb</a>
    {% endblock %}

oboero/templates/verb/question.html
    {% extends "_layout/_base.html" %}

    {% block css %}
    {% endblock %}
    {% block js %}
    {% endblock %}
    {% block content %}
    <blockquote>
        {{ question }}
    </blockquote>
    <form>
        <select name="answer">
            {% for c in choices['options'] %}
            <option value="{{ c }}" {% if c == choices['answer'] %}selected{% endif %}>{{ c }}</option>
            {% endfor %}
        </select>
    </form>
    {% endblock %}