oboero/views/index.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import render_template, request, session, current_app, make_response
from flask.blueprints import Blueprint
from flask.ext.login import login_user, logout_user, current_user
import random
import json

from .. import db
from oboero.models.user import User
from oauth2client.client import flow_from_clientsecrets, FlowExchangeError
blueprint = Blueprint('index', __name__)


@blueprint.route('/')
def game():
    state = ''.join(random.choice("abcdefghijklmnopqrstuvwxyz0123456789")
                    for x in xrange(32))

    session['state'] = state
    client_id = current_app.config['CLIENT_ID']
    return render_template('game.html', verbs=[], total=0,
                           client_id=client_id, state=state)


@blueprint.route('/about')
def about():
    return render_template('about.html')


@blueprint.route('/profile')
def profile():
    assert current_user is not None
    return render_template('profile.html')

@blueprint.route('/save_profile', methods=['POST'])
def save_profile():
    _pic_url = request.form.get('pic_url')
    user_email = request.form.get('user_email', current_user.email)
    user = db.session.query(User).get(user_email)
    if not user:
        user = User(email=user_email, username=user_email.split('@')[0], pic_url=_pic_url.split('?sz')[0] + "?sz=70")
        db.session.add(user)
        db.session.commit()
    elif not user.pic_url:
        user.pic_url = pic_url=_pic_url.split('?sz')[0] + "?sz=70"
        db.session.commit()
    response = make_response(json.dumps('PICTURE SAVED'), 200)
    response.headers['Content-Type'] = 'application/json'
    return response

@blueprint.route('/change_name', methods=['POST'])
def change_name():
    user = db.session.query(User).get(current_user.email)
    new_username = request.form.get('new_name') or "Incognito"
    new_username = new_username.strip()
    user.username = new_username
    db.session.commit()
    response = make_response(json.dumps('NAME SAVED'), 200)
    response.headers['Content-Type'] = 'application/json'
    return response

@blueprint.route('/connect', methods=['POST'])
def login():
    # currently supported login options: Google Plus

    if request.args.get('state', '') != session['state']:
        response = make_response(json.dumps('Invalid state parameter.'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    # del session['state']
    code = request.data

    try:
        g_scopes = ['https://www.googleapis.com/auth/plus.login',
                    'https://www.googleapis.com/auth/plus.profile.emails.read']
        oauth_flow = flow_from_clientsecrets('client_secrets.json',
                                             scope=' '.join(g_scopes))
        oauth_flow.redirect_uri = 'postmessage'
        credentials = oauth_flow.step2_exchange(code)

    except FlowExchangeError:
        response = make_response(
            json.dumps('Failed to upgrade authorization code'), 401)
        response.headers['Content-Type'] = 'application/json'
        return response

    gplus_id = credentials.id_token['sub']
    stored_credentials = session.get('credentials')
    stored_gplus_id = session.get('gplus_id')
    if stored_credentials is not None and gplus_id == stored_gplus_id:
        response = make_response(json.dumps('User is already connected'), 200)
        response.headers['Content-Type'] = 'application/json'
        return response

    session['credentials'] = credentials
    session['gplus_id'] = gplus_id

    user_email = credentials.id_token['email']
    user = db.session.query(User).get(user_email)
    if not user:
        # create user account in our db
        user = User(email=user_email, username=user_email.split('@')[0])
        db.session.add(user)
        db.session.commit()
    session['user'] = user
    login_user(user)

    response = make_response(json.dumps('Logged In!'), 200)
    response.headers['Content-Type'] = 'application/json'
    return response


@blueprint.route('/logout', methods=['POST'])
def logout():
    credentials = session.get('credentials')
    if credentials:
        session.pop('credentials')
    if session.get('gplus_id'):
        session.pop('gplus_id')
    logout_user()
    print(current_user.is_authenticated())
    response = make_response(json.dumps('SIGNED OUT'), 200)
    response.headers['Content-Type'] = 'application/json'
    return response

oboero/templates/about.html
    {% extends "_layout/_base.html" %}
    {% block content %}
	<section id="about">
		<div class="hero" style="padding-bottom: 50px;">
			<a href="/" class="image"><img class="logo" src="/static/img/oboero_min.png"></a>
			<h1>About OBOERO</h1>
			<p>
				<dl>
					<dt>OBOERO 覚えろ</dt>
					<dd><i>[imperative form]</i> to remember or memorise.<br>When used wisely with an authoritative voice, it may come across as "Why don't you !@#$ remember stuff?"</dd>
					<br>
					<dd>A fun-packed Japanese language quiz where verb conjugation champs can pit their skils over their favourite ramen.</dd>
				</dl>
				<small>** Built with <a href="http://flask.pocoo.org/">Flask (an awesome Python microframework!)</a>, HTML5, CSS3 and jQuery **</small>
			</p>
		</div>
		<div style="padding-bottom: 50px;">
			<a class="image profile" href="http://kelvintaywl.tumblr.com" target="_blank"><img class="main logo profile" src="/static/img/face_min.png"></a>
			<h2>About Kelvin Tay</h2>
			<p>
				I love learning languages, I'm just not good at them. That's why I built this for my own amusement.<br><br>Currently working as a mobile application engineer in Tokyo, I guess you can say that I eat, drink and sleep Japanese. Yes, you can address me as Kerubin-san (ケルビンさん)<br><br>
				If you would like to chat, write me a nice <a href="mailto:kelvintaywl@gmail.com?subject=Oboero+This!">email</a>, or visit <a class="image" href="http://www.tinyurl.com/kelvintaywl"><button>my micro-portfolio</button></a>.<br>
			</p>
		</div>
	</section>
    {% endblock %}
	{% block js %}
	$(document).ready(function(){
		$('button#submitButton').click(function(){
			textInput = $('input.answer').val();
			answer = $('input.answer').attr('data-answer');
			if(textInput == answer){
				alert('CONGRATS');
			}
			else{
				alert('LAME');
			}
		});
	});
    {% endblock %}

oboero/templates/game.html
    {% extends "_layout/_base.html" %}
    {% block head %}
    {% endblock %}

    {% block content %}
	<section id="splash">
        <div id="intro-text">
            <p>日本語が苦手？ 大丈夫だね! これから、<a href="{{url_for('index.about')}}">「覚えろ」</a></p>
            <p>Level up your Japanese by fighting the Grammar Yakuzas. Become a Respectable Gaijin!
                <div id="gConnect">
                    <button class="g-signin"
                        data-scope="https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read"
                        data-requestvisibleactions="http://schemas.google.com/AddActivity"
                        data-clientId="{{ client_id }}"
                        data-accesstype="offline"
                        data-callback="onSignInCallback"
                        data-theme="dark"
                        data-cookiepolicy="single_host_origin">
                    </button>
                </div>
            </p>
        </div>
        <div class="floater"></div>
            <div class="hexagon-set">
            <div class="hero">
                <div class="hexagons">
                    <div id="logo-front" class="hexagon"></div>
                    <div id="logo-back" class="hexagon"></div>
                </div>
            </div>
		</div>
	</section>
    <section id="profile-page" style="display: none">
        <nav class="pure-menu pure-menu-open pure-menu-horizontal">
            <a href="#" class="pure-menu-heading">「覚えろ」</a>

            <ul>
                <li><a href="{{ url_for('index.about') }}"><i class="fa fa-cube"></i>&nbsp;About</a></li>
                <li><a href="http://github.com/kelvintaywl/oboero"><i class="fa fa-github"></i>&nbsp;Github</a></li>
                <li><a onclick="logout()"><i class="fa fa-sign-out"></i>&nbsp;logout</a></li>
            </ul>
        </nav>
        <div class="pure-g" style="margin-top: 50px;">
            <div class="pure-u-md-1-3">
                <div class="placard">
                    <img src="static/img/kanji.png">
                    <div class="pure-menu pure-menu-open">
                        <a class="pure-menu-heading"><h4>Kanji Crush Saga</h4></a>

                        <ul>
                            <li><a><progress max="100" value="50"></progress></a></li>
                            <li><a href="#">CONTINUE</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="pure-u-md-1-3">
                <div class="placard">
                    <img src="static/img/wordcount_min.png">
                    <div class="pure-menu pure-menu-open">
                        <a class="pure-menu-heading"><h4>Dictionary Master</h4></a>

                        <ul>
                            <li><a><progress max="100" value="75"></progress></a></li>
                            <li><a href="#">CONTINUE</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="pure-u-md-1-3">
                <div class="placard">
                    <img src="static/img/verbconju.png">
                    <div class="pure-menu pure-menu-open">
                        <a class="pure-menu-heading"><h4>Verb Conjugator</h4></a>

                        <ul>
                            <li><a><progress max="100" value="50"></progress></a></li>
                            <li><a href="#">CONTINUE</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
	{% block js %}
        $(document).ready(function(){
            $('.hero').click(function(){
                $('#gConnect button').trigger('click');
            });
        });
    {% endblock %}

oboero/templates/login.html
{% extends "_layout/_base.html" %}
{% block content %}
<form class="pure-form" action="" method="post">
	<input type="hidden" name="next_page" value="{{next_page}}">
    <fieldset class="pure-group">
        <input type="email" name="email" class="pure-input-1-2" placeholder="email">
    </fieldset>

    <button type="submit" class="pure-button pure-input-1-2 pure-button-primary">Sign in</button>
</form>
{% endblock %}

oboero/templates/profile.html
{% extends "_layout/_base.html" %}
{% block head %}
{% endblock %}

{% block content %}
<section id="profile-page">
        <nav class="pure-menu pure-menu-open pure-menu-horizontal">
            <a href="#" class="pure-menu-heading">「覚えろ」</a>

            <ul>
                <li><a href="{{ url_for('index.about') }}"><i class="fa fa-cube"></i>&nbsp;About</a></li>
                <li><a href="http://github.com/kelvintaywl/oboero"><i class="fa fa-github"></i>&nbsp;Github</a></li>
                <li><a onclick="logout()"><i class="fa fa-sign-out"></i>&nbsp;logout</a></li>
                <li> Welcome {{ current_user.username }}</li>
            </ul>
            <div id = "profile-icon" class="pure-menu-heading" style="float: right"><img src= "{{  current_user.pic_url }}" class = "circular-profile"></div>
        </nav>
        <div class="pure-g" style="margin-top: 50px;">
            <div class="pure-u-md-1-3">
                <div class="placard">
                    <img src="static/img/kanji.png">
                    <div class="pure-menu pure-menu-open">
                        <a class="pure-menu-heading"><h4>Kanji Crush Saga</h4></a>

                        <ul>
                            <li><a><progress max="100" value="50"></progress></a></li>
                            <li><a href="#">CONTINUE</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="pure-u-md-1-3">
                <div class="placard">
                    <img src="static/img/wordcount_min.png">
                    <div class="pure-menu pure-menu-open">
                        <a class="pure-menu-heading"><h4>Dictionary Master</h4></a>

                        <ul>
                            <li><a><progress max="100" value="75"></progress></a></li>
                            <li><a href="#">CONTINUE</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="pure-u-md-1-3">
                <div class="placard">
                    <img src="static/img/verbconju.png">
                    <div class="pure-menu pure-menu-open">
                        <a class="pure-menu-heading"><h4>Verb Conjugator</h4></a>

                        <ul>
                            <li><a><progress max="100" value="50"></progress></a></li>
                            <li><a href="#">CONTINUE</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!-- NOTE: this is for testing of Google's API client. Re-prettify it soon!
        ''' -->
        <div id="profile"></div>
        <div id="profileDialog">
            <div id="profileDialogContent">
                <div style=" display: inline-block; position:relative">
                    <img src= "{{  current_user.pic_url }}"/>
                   <!--<div style=" display: inline-block; width: 70px; background-color: powderblue; opacity: 0.7; position:absolute; left: 10px; top: 60px;">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fa fa-edit"></i>
                    </div>-->
                </div>
                <div id="profile-name"> <p contenteditable="true"> {{current_user.username }}</p>&nbsp;<i class="fa fa-edit"></i></div>
                <div id="profileDialogButton">
                    <a class="button-small button-success pure-button" href="#" onclick="editProfile();" style="margin-left: 106px">Submit</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block js %}

    $(document).ready(function() {
        var open = false;
        $("#profileDialogContent").hide();
        $("#profileDialogButton").hide();
        $('body').click(function(event) {
            //Hide the menus if visible
            if(event.target.id != 'profile-icon' && !!open){
                $('#profileDialog').animate({
                    height: '0px'},
                    200,
                    function(ctnr){
                        $("#profileDialogContent").hide();
                        $("#profileDialogButton").hide();
                    }
                );
                open = !open;
            }
        });

        $('#profile-icon').click(function (event) {
            event.stopPropagation();
            if(!open) {
                var autoHeight = $('#profileDialogContent').height();
                $('#profileDialog').animate({
                    height: autoHeight},
                    200,
                    function(ctnr){
                        $("#profileDialogContent").show();
                        $("#profileDialogButton").show();
                    }
                );
            } else {
                $('#profileDialog').animate({
                    height: '0px'},
                    200,
                    function(ctnr){
                        $("#profileDialogContent").hide();
                        $("#profileDialogButton").hide();
                    }
                );
            };
            open = !open;
        });
        $('#profileDialog').click(function (event) {
            event.stopPropagation();
        });
    });


    function editProfile(){
        var _new_name = $('#profile-name').children("p").text();
        $.ajax({
            type: 'POST',
            data :{
                new_name: _new_name,
             },
            url: '{{url_for('index.change_name')}}',
            success: function(data){
                window.location.href = "{{url_for('index.profile')}}";
            }
        });
    }
    /*
    var signOut = function(){
        gapi.auth.signOut();
        $.ajax({
            type: 'POST',
            data :{
                pic-url: "url",
             },
            url: '{{url_for('index.logout')}}',
            success: function(data){
                alert(data);
                window.location.href = "{{url_for('index.game')}}";
            }
        });
    };
    */

{% endblock %}

oboero/templates/search.html
<html>
<head>
	<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.2.1/pure-min.css">
	<link rel="stylesheet" href="/static/main.css">
	<title>OBOERO 覚えろ</title>
	<link rel="icon" href="/static/img/favicon.ico?v=2">
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width,minimum-scale=1,maximum-scale=1">
	<meta name="description" content="OBOERO! Verb Conjugator" />
	<meta name="author" content="kelvintaywl@gmail.com" />
</head>
<body>
	<img style="display:block; margin: 0 auto;" src="/static/img/oboero_min.png">
	<small style="display:block;text-align:center;margin: 10 auto;">VERB CONJUGATOR</small>
	<div class="modal">
		<h1>About OBOERO</h1>
		<h2>Verb: {{verb['jap']}}ます</h2>
		<h2>Nai: {{verb['nai']}}</h2>
		<h2>Plain: {{verb['plain']}}</h2>
		<h2>Te: {{verb['te']}}</h2>
		<h3>Conditional: {{verb['conditional']}}</h3>
		<h3>Volitional: {{verb['volitional']}}</h3>
		<h3>Imperative: {{verb['imperative']}}</h3>
		<h3>Prohitive: {{verb['prohibitive']}}</h3>
		<!--
		<form>
			<fieldset>
			<label for="verb">Name</label>
			<input type="text" name="verb" value="やります" placeholder="[ます form]">
			</fieldset>
			<fieldset>
			<input type="submit" value="submit" id="submitButton">
			</fieldset>
		</form>
		-->
		<footer><img class="main" src="/static/img/face_min.png"><small>2013. Made with love by <a href="http://www.tinyurl.com/kelvintaywl">Kelvin Tay</a></small></footer>
	</div>
	<script>
	</script>
</body>
</html>